export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_START = "REGISTER_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_START = "LOGIN_START";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const REMOVE_ERRORS = "REMOVE_ERRORS";
export const USER_DELETE = "USER_DELETE";
export const USER_UPDATE = "USER_UPDATE";
export const LOGOUT = "LOGOUT";

//todo and collections
export const FETCH_TODO_START = "FETCH_TODO_START";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_TODO_FAIL = "FETCH_TODO_FAIL";
export const FETCH_COLLECTION_START = "FETCH_COLLECTION_START";
export const FETCH_COLLECTION_FAIL = "FETCH_COLLECTION_FAIL";
export const FETCH_COLLECTION_SUCCESS = "FETCH_COLLECTION_SUCCESS";
export const REMOVE_TODO_ERROR = "REMOVE_TODO_ERROR";
export const POST_COLLECTION_START = "POST_COLLECTION_START";
export const POST_COLLECTION_FAIL = "POST_COLLECTION_FAIL";
export const POST_COLLECTION_SUCCESS = "POST_COLLECTION_SUCCESS";

export const DELETE_COLLECTION_START = "DELETE_COLLECTION_START";
export const DELETE_COLLECTION_FAIL = "DELETE_COLLECTION_FAIL";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";

export const UPDATE_COLLECTION_START = "UPDATE_COLLECTION_START";
export const UPDATE_COLLECTION_FAIL = "UPDATE_COLLECTION_FAIL";
export const UPDATE_COLLECTION_SUCCESS = "UPDATE_COLLECTION_SUCCESS";

export const POST_TODO_START = "POST_TODO_START";
export const POST_TODO_FAIL = "POST_TODO_FAIL";
export const POST_TODO_SUCCESS = "POST_TODO_SUCCESS";

export const DELETE_TODO_START = "DELETE_TODO_START";
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";

export const UPDATE_TODO_START = "UPDATE_TODO_START";
export const UPDATE_TODO_FAIL = "UPDATE_TODO_FAIL";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";

export const BOOLEAN_TODO_START = "UPDATE_TODO_START";
export const BOOLEAN_TODO_FAIL = "UPDATE_TODO_FAIL";
export const BOOLEAN_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";

//plan and collections
export const FETCH_PLAN_START = "FETCH_PLAN_START";
export const FETCH_PLAN_SUCCESS = "FETCH_PLAN_SUCCESS";
export const FETCH_PLAN_FAIL = "FETCH_PLAN_FAIL";
export const FETCH_PLAN_COLLECTION_START = "FETCH_PLAN_COLLECTION_START";
export const FETCH_PLAN_COLLECTION_FAIL = "FETCH_PLAN_COLLECTION_FAIL";
export const FETCH_PLAN_COLLECTION_SUCCESS = "FETCH_PLAN_COLLECTION_SUCCESS";
export const REMOVE_PLAN_ERROR = "REMOVE_PLAN_ERROR";
export const POST_PLAN_COLLECTION_START = "POST_PLAN_COLLECTION_START";
export const POST_PLAN_COLLECTION_FAIL = "POST_PLAN_COLLECTION_FAIL";
export const POST_PLAN_COLLECTION_SUCCESS = "POST_PLAN_COLLECTION_SUCCESS";

export const DELETE_PLAN_COLLECTION_START = "DELETE_PLAN_COLLECTION_START";
export const DELETE_PLAN_COLLECTION_FAIL = "DELETE_PLAN_COLLECTION_FAIL";
export const DELETE_PLAN_COLLECTION_SUCCESS = "DELETE_PLAN_COLLECTION_SUCCESS";

export const UPDATE_PLAN_COLLECTION_START = "UPDATE_PLAN_COLLECTION_START";
export const UPDATE_PLAN_COLLECTION_FAIL = "UPDATE_PLAN_COLLECTION_FAIL";
export const UPDATE_PLAN_COLLECTION_SUCCESS = "UPDATE_PLAN_COLLECTION_SUCCESS";

export const POST_PLAN_START = "POST_PLAN_START";
export const POST_PLAN_FAIL = "POST_PLAN_FAIL";
export const POST_PLAN_SUCCESS = "POST_PLAN_SUCCESS";

export const DELETE_PLAN_START = "DELETE_PLAN_START";
export const DELETE_PLAN_FAIL = "DELETE_PLAN_FAIL";
export const DELETE_PLAN_SUCCESS = "DELETE_PLAN_SUCCESS";

export const UPDATE_PLAN_START = "UPDATE_PLAN_START";
export const UPDATE_PLAN_FAIL = "UPDATE_PLAN_FAIL";
export const UPDATE_PLAN_SUCCESS = "UPDATE_PLAN_SUCCESS";

export const BOOLEAN_PLAN_START = "UPDATE_PLAN_START";
export const BOOLEAN_PLAN_FAIL = "UPDATE_PLAN_FAIL";
export const BOOLEAN_PLAN_SUCCESS = "UPDATE_PLAN_SUCCESS";

//user

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const REMOVE_USER_ERRORS = "REMOVE_USER_ERRORS";

//chart types

export const GET_TODO_CHART_START = "GET_TODO_CHART_START";
export const GET_TODO_CHART_FAIL = "GET_TODO_CHART_FAIL";
export const GET_TODO_CHART_SUCCESS = "GET_TODO_CHART_SUCCESS";

export const GET_PLAN_CHART_START = "GET_PLAN_CHART_START";
export const GET_PLAN_CHART_FAIL = "GET_PLAN_CHART_FAIL";
export const GET_PLAN_CHART_SUCCESS = "GET_PLAN_CHART_SUCCESS";

export const REMOVE_TODO_CHART_ERROR = "REMOVE_TODO_CHART_ERROR";
export const REMOVE_PLAN_CHART_ERROR = "REMOVE_PLAN_CHART_ERROR";
